---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- Media & Storage:
    - Jellyfin:
        href: http://{{HOMEPAGE_VAR_JELLYFIN_URL}}:8096/
        icon: jellyfin.svg
        description: Multimedia Service
        widget:
          type: jellyfin
          url: http://{{HOMEPAGE_VAR_JELLYFIN_URL}}:8096
          key: {{HOMEPAGE_VAR_JELLYFIN_KEY}}
          enableBlocks: true
          enableNowPlaying: true
          enableUser: true
          showEpisodeNumber: true
          expandOneStreamToTwoRows: true

    - OpenMediaVault:
        href: http://{{HOMEPAGE_VAR_OMV_URL}}/
        icon: openmediavault.svg
        description: Open network attached storage solution
        widget:
          type: openmediavault
          url: http://{{HOMEPAGE_VAR_OMV_URL}}
          username: {{HOMEPAGE_VAR_OMV_USERNAME}}
          password: {{HOMEPAGE_VAR_OMV_PASSWORD}}
          method: services.getStatus # required

- Home:
    - Home Assistant:
        href: http://{{HOMEPAGE_VAR_HASS_URL}}:8123/
        icon: home-assistant.svg
        description: Open source home automation
        widget:
          type: homeassistant
          url: http://{{HOMEPAGE_VAR_HASS_URL}}:8123
          key: {{HOMEPAGE_VAR_HASS_KEY}}

    - OctoPrint:
        href: http://{{HOMEPAGE_VAR_OCTOPRINT_URL}}/
        icon: octoprint.svg
        description: Remote 3D printer management software
        widget:
          type: octoprint
          url: http://{{HOMEPAGE_VAR_OCTOPRINT_URL}}
          key: {{HOMEPAGE_VAR_OCTOPRINT_KEY}}

- Tools & Admin:
    - ChangeDetection.io:
        href: http://{{HOMEPAGE_VAR_CD_URL}}:5000/
        icon: changedetection.svg
        description: Monitor websites changes
        widget:
          type: changedetectionio
          url: http://{{HOMEPAGE_VAR_CD_URL}}:5000
          key: {{HOMEPAGE_VAR_CD_KEY}}

    - Proxmox:
        href: https://{{HOMEPAGE_VAR_PROXMOX_URL}}:8006/
        icon: proxmox.svg
        description: Powerful open-source server solutions
        widget:
          type: proxmox
          url: https://{{HOMEPAGE_VAR_PROXMOX_URL}}:8006
          username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
          password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}

    - Proxmox Backup Server:
        href: https://{{HOMEPAGE_VAR_PBS_URL}}:8007/
        icon: proxmox-light.svg
        description: Proxmox backup solution.
  
    - Tailscale:
        href: https://login.tailscale.com/admin/machines
        icon: tailscale.png
        description: Mesh VPN service